// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  history: dynamic(() => import("./History")),
  image: dynamic(() => import("./Image")),
  post_list: dynamic(() => import("./PostList")),
  post_references: dynamic(() => import("./PostInfo")),
  project_main: dynamic(() => import("./Content")),
};
